import type {Metadata, NextPage} from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProvidersServer from "@/components/providers-server";
import ProvidersClient from "@/components/providers-client";
import {PropsWithChildren} from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout:NextPage<Readonly<PropsWithChildren>> = ({
children
}) => {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProvidersServer>
          <ProvidersClient>
            {children}
          </ProvidersClient>
        </ProvidersServer>
      </body>
    </html>
  );
}

export default RootLayout;